#pragma config(Sensor, dgtl2,  RIGHT_ENCODER,  sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  LEFT_ENCODER,   sensorQuadEncoder)
#pragma config(Motor,  port3,  motorLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  motorRight,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#define max_Ticks_per_sec 1450
#define LEFT_MOTOR motor[motorLeft]
#define RIGHT_MOTOR motor[motorRight]

// PID variables
int error, prevError = 0;
int integral = 0;
int derivative = 0;

// Global motor offsets
int leftMotorOffset = 5;  // Adjust as needed
int rightMotorOffset = 0; // Adjust as needed

void resetEncoders() {
    SensorValue[LEFT_ENCODER] = 0;
    SensorValue[RIGHT_ENCODER] = 0;
}

int getLeftEncoderSpeed() {
    int initialTicks = SensorValue[LEFT_ENCODER];
    wait1Msec(10);
    int finalTicks = SensorValue[LEFT_ENCODER];
    int currentTicks_per_sec = (finalTicks - initialTicks) * 100;
    return (currentTicks_per_sec * 127) / max_Ticks_per_sec;
}

int getRightEncoderSpeed() {
    int initialTicks = SensorValue[RIGHT_ENCODER];
    wait1Msec(10);
    int finalTicks = SensorValue[RIGHT_ENCODER];
    int currentTicks_per_sec = (finalTicks - initialTicks) * 100;
    return (currentTicks_per_sec * 127) / max_Ticks_per_sec;
}

int computePID(int desiredSpeed, int actualSpeed) {
    error = desiredSpeed - actualSpeed;
    integral += error;
    derivative = error - prevError;
    prevError = error;
    
    int output = (0.5 * error) + (0.01 * integral) + (0.1 * derivative);
    if (output > 127) output = 127;
    if (output < -127) output = -127;
    
    return output;
}

void resetPID() {
    error = 0;
    prevError = 0;
    integral = 0;
    derivative = 0;
}

void setMotorPower(int leftPower, int rightPower) {
    LEFT_MOTOR = leftPower + leftMotorOffset;
    RIGHT_MOTOR = rightPower + rightMotorOffset;
}

void stopMotors() {
    int leftTicks = SensorValue[LEFT_ENCODER];
    int rightTicks = SensorValue[RIGHT_ENCODER];

    if (leftTicks > rightTicks) {
        RIGHT_MOTOR = 10;
        wait1Msec(100);
    } else if (rightTicks > leftTicks) {
        LEFT_MOTOR = 10;
        wait1Msec(100);
    }

    LEFT_MOTOR = -10;
    RIGHT_MOTOR = -10;
    wait1Msec(100);

    LEFT_MOTOR = 0;
    RIGHT_MOTOR = 0;
}

void moveForward(int speed, int duration) {
    resetPID();
    resetEncoders();
    int startTime = nSysTime;

    while (nSysTime - startTime < duration - 500) {
        int leftPower = computePID(speed, getLeftEncoderSpeed());
        int rightPower = -computePID(speed, getRightEncoderSpeed());
        setMotorPower(leftPower, rightPower);
    }

    for (int i = 0; i <= 10; i++) {
        setMotorPower((LEFT_MOTOR * (10 - i)) / 10, (RIGHT_MOTOR * (10 - i)) / 10);
        wait1Msec(50);
    }
    stopMotors();
}

void moveBackward(int speed, int duration) {
    resetPID();
    resetEncoders();
    int startTime = nSysTime;

    while (nSysTime - startTime < duration) {
        int leftPower = -computePID(speed, getLeftEncoderSpeed());
        int rightPower = computePID(speed, getRightEncoderSpeed());
        setMotorPower(leftPower, rightPower);
    }
    stopMotors();
}

void turnLeft(int speed, int duration) {
    resetPID();
    resetEncoders();
    int startTime = nSysTime;

    while (nSysTime - startTime < duration) {
        int leftPower = -computePID(speed, getLeftEncoderSpeed());
        int rightPower = -computePID(speed, getRightEncoderSpeed());
        setMotorPower(leftPower, rightPower);
    }
    stopMotors();
}

void turnRight(int speed, int duration) {
    resetPID();
    resetEncoders();
    int startTime = nSysTime;

    while (nSysTime - startTime < duration) {
        int leftPower = computePID(speed, getLeftEncoderSpeed());
        int rightPower = computePID(speed, getRightEncoderSpeed());
        setMotorPower(leftPower, rightPower);
    }
    stopMotors();
}

task main() {
    moveForward(-127, 2000);
    stopMotors();
}
