#pragma config(Sensor, dgtl9,  IR_A, sensorDigitalIn)
#pragma config(Sensor, dgtl10, IR_B, sensorDigitalIn)
#pragma config(Sensor, dgtl11, IR_C, sensorDigitalIn)
#pragma config(Sensor, dgtl12, IR_D, sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


readIRValues(void){
    while (true){
        int IR_A_VALUE = SensorValue[IR_A]; 
        int IR_B_VALUE = SensorValue[IR_B]; 
        int IR_C_VALUE = SensorValue[IR_C]; 
        int IR_D_VALUE = SensorValue[IR_D]; 
        wait1Msec(50); // read IR values every 50ms
    }
    // Print digital sensor value to debug stream
    writeDebugStreamLine("IR_A: %d", IR_A_VALUE);
    writeDebugStreamLine("IR_B: %d", IR_B_VALUE);
    writeDebugStreamLine("IR_C: %d", IR_C_VALUE);
    writeDebugStreamLine("IR_D: %d", IR_D_VALUE);
}

ObstacleAvoidance(IR_A_VALUE, IR_B_VALUE, IR_C_VALUE, IR_D_VALUE){

    int IR_State = 0;

    if (IR_A_VALUE == 0 && IR_B_VALUE == 0 && IR_C_VALUE == 1 && IR_D_VALUE == 1) {
        IR_State = 1;  // Represents case 1
    } else if (IR_A_VALUE == 0 && IR_B_VALUE == 1 && IR_C_VALUE == 0 && IR_D_VALUE == 0) {
        IR_State = 2;  // Represents case 2
    } else if (IR_A_VALUE == 1 && IR_B_VALUE == 0 && IR_C_VALUE == 1 && IR_D_VALUE == 0) {
        IR_State = 3;  // Represents case 3
    } else if (IR_A_VALUE == 1 && IR_B_VALUE == 1 && IR_C_VALUE == 0 && IR_D_VALUE == 0) {
        IR_State = 4;  // Represents case 4
    }
    
    switch (IR_State) {
        case 1:
            // Code block for (IR_A_VALUE == 0 && IR_B_VALUE == 0 && IR_C_VALUE == 1 && IR_D_VALUE == 1)
            break;
        
        case 2:
            // Code block for (IR_A_VALUE == 0 && IR_B_VALUE == 1 && IR_C_VALUE == 0 && IR_D_VALUE == 0)
            break;
        
        case 3:
            // Code block for (IR_A_VALUE == 1 && IR_B_VALUE == 0 && IR_C_VALUE == 1 && IR_D_VALUE == 0)
            break;
    
        case 4:
            // Code block for (IR_A_VALUE == 1 && IR_B_VALUE == 1 && IR_C_VALUE == 0 && IR_D_VALUE == 0)
            break;
        
        default:
            // do nothing just break
            break;
    }
    
}

task main() {

   
}
