#pragma config(Sensor, in1,    sharpTC,        sensorAnalog)
#pragma config(Sensor, in2,    sharpBL,        sensorAnalog)
#pragma config(Sensor, in3,    sharpBC,        sensorAnalog)
#pragma config(Sensor, in4,    sharpBR,        sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Function to get the average analog sensor value over multiple samples
float getMeanAnalogValue(tSensors sensor, int samples = 30) {
    int sum = 0;

    for (int i = 0; i < samples; i++) {
        sum += SensorValue[sensor]; // Read sensor value
        wait1Msec(10); // Short delay to reduce fluctuations
    }

    return sum / samples; // Return the average
}

// Function to convert analog sensor value to voltage
float convertToVoltage(int analogValue) {
    return (analogValue * 5.0) / 4095.0;  // Convert ADC value to voltage
}

// Function to convert voltage to distance based on sensor type
float getDistance(tSensors sensor, int analogValue) {
    if (analogValue == 0) return 80.0; // Prevent division by zero

    float voltage = convertToVoltage(analogValue);
    float distance = 0.0;

    // Select calibration formula based on the sensor type
    if (sensor == sharpTC) {
        distance = 25.99 / pow(voltage, 1.22); // sharpTC formula
    }
    else if (sensor == sharpBR) {
        distance = 28.37 / pow(voltage, 1.08); // sharpBR formula
    }
    else if (sensor == sharpBL) {
        distance = 26.82 / pow(voltage, 1.28); // sharpBL formula
    }
    else if (sensor == sharpBC) {
        distance = 10.02 / pow(voltage, 1.26); // sharpBC formula
    }

    return distance;
}

// Main task to print the averaged sensor values and distances
task main() {
    while (true) {
        // Get the averaged sensor values
        int meanBL = getMeanAnalogValue(sharpBL);
        int meanBR = getMeanAnalogValue(sharpBR);
        int meanTC = getMeanAnalogValue(sharpTC);
        int meanBC = getMeanAnalogValue(sharpBC);

        // Convert to distance by passing both sensor and analog value
        float distBL = getDistance(sharpBL, meanBL);
        float distBR = getDistance(sharpBR, meanBR);
        float distTC = getDistance(sharpTC, meanTC);
        float distBC = getDistance(sharpBC, meanBC);

        // Print the values to the debug stream
        writeDebugStreamLine("Sensor BL: %.2f, Distance BL: %.2f cm", meanBL, distBL);
        writeDebugStreamLine("Sensor BR: %.2f, Distance BR: %.2f cm", meanBR, distBR);
        writeDebugStreamLine("Sensor TC: %.2f, Distance TC: %.2f cm", meanTC, distTC);
        writeDebugStreamLine("Sensor BC: %.2f, Distance BC: %.2f cm", meanBC, distBC);
				writeDebugStreamLine("------------------------------------------------------");
        wait1Msec(500); // Delay before next reading
    }
}
